/**
 * controllers/generate-spec.ts
 * ----------------------------------------------------------------
 * Client-side HTTP wrapper for the generate-spec edge function.
 * Runs in the plugin iframe -- NOT backend.
 */

import { SUPABASE_CONFIG, anonHeaders } from '@figma-forge/shared/services'
import type { ExportedFrame } from '@figma-forge/shared/services'
import type { SpecResult } from '../types'

export interface GenerateSpecParams {
  /** Description of the product/feature to be documented. */
  context: string
  /** Frames exported by the main thread (base64 JPEG). */
  frames: ExportedFrame[]
}

/**
 * Calls the `generate-spec` edge function on Supabase and returns
 * the structured spec generated by the LLM.
 *
 * @param params - text context + exported frames
 * @returns the SpecResult
 * @throws Error if the request fails or the server returns non-2xx
 */
export async function generateSpec(
  params: GenerateSpecParams,
): Promise<SpecResult> {
  const { context, frames } = params

  if (!frames.length) throw new Error('No frames selected.')
  if (!context.trim()) throw new Error('Context is required.')

  const mappedFrames = frames.map(f => ({
    name: f.name,
    imageBase64: f.imageBase64,
  }))

  const url = `${SUPABASE_CONFIG.URL}/functions/v1/generate-spec`

  const res = await fetch(url, {
    method: 'POST',
    headers: anonHeaders(),
    body: JSON.stringify({ context, frames: mappedFrames }),
  })

  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`HTTP ${res.status} [${url}]: ${text || res.statusText}`)
  }

  return (await res.json()) as SpecResult
}
